### ISSUE TITLE
Hot reloading not working

### ISSUE THREAD

**Issue by renspoesse** [eddyerburgh/vue-cli-ssr-example#3]
When starting the development server with `yarn serve`, hot reloading changes doesn't seem to work. Looking at the startup scripts I'm also not sure how it would, but `server.js` code indicates that it should.

Could you provide any direction @eddyerburgh ?

**Comment by jonaskuske** [comment]
Since `server.js` only requires `vue-ssr-server-bundle.json` once and uses that bundle from then on, I don't see how hot-reloading (the server renderer) should work here.

You can check out the [offical Vue Hackernews app](https://github.com/vuejs/vue-hackernews-2.0/blob/master/build/setup-dev-server.js) to see how they're doing it there, it's also linked in [the official Vue docs as reference](https://ssr.vuejs.org/guide/build-config.html#server-config) for implementing hot-reload with SSR.

**Comment by Yamaha32088** [comment]
I changed line 25 of server.js to:
`renderer = createRenderer(JSON.parse(bundle), {
  template,
  clientManifest
})`

It seems to work fine for me although I see a message during startup that says `1 null`

**Comment by Pong420** [comment]
i think the root cause is here
https://github.com/eddyerburgh/vue-cli-ssr-example/blob/d8a24a2479cabb67de91f99fa6301fefe987c11c/src/entry-client.js#L5

i should be
```js
router.onReady(() => {
  app.$mount("#app");
});
```
